#! /usr/bin/env perl

use strict;
use warnings;

my @indices;
my $header = 1;

while (<STDIN>) {
  chomp;
  my @fields = split("\t");
  if ( $header ) {
    my %indices;
    for (my $i=1; $i<=$#fields; $i++) {
      $indices{$fields[$i]} = $i;
    }
    @indices = (0);
    foreach my $sample ( @ARGV ) {
      my $i = $indices{$sample};
      if ( !defined($i) ) {
	print STDERR "Cannot find sample in counts: $sample\n";
	exit(1);
      }
      push @indices, $i;
    }
    $header = 0;
  }
  my @l = ();
  foreach my $i ( @indices ) {
    push @l, $fields[$i];
  }
  print join("\t",@l),"\n";
}

